name: 'Git Delta Action'
description: 'Show git diff with delta for a specific files against environments/branches/commits'
inputs:
  github_token:
    description: 'Github token for query github rest api if compare against environments'
    required: false
  environment:
    description: 'Environment to compare against'
    required: false
  branch:
    description: 'Base branch to compare against'
    required: false
    default: 'main'
  commit:
    description: 'Commit to compare against'
    required: false
  includes:
    description: |
      "File patterns to include in the delta calculation, separated by newlines `\n`"
      For example: 
        includes: |
          live/local/*
          live/stag/ec2/terragrunt.hcl
    required: false
    default: ""
  excludes:
    description: |
      "File patterns to exclude in the delta calculation, separated by newlines `\n` Note excludes are applied after includes."
      For example: 
        excludes: |
          *.zip
          */**/README.md
    required: false
    default: ""
  online:
    description: |
      "If true, git delta will be run online against the GitHub API, otherwise it will be run offline"
    required: false
    default: true
outputs:
  delta_files:
    description: "File paths with the delta as json string format"
  is_detected:
    description: "Bool to show if delta has been detected"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jerry153fish/git-delta:v0.0.2'
